from television import Television
def test_channel():
    tv = Television()
    tv.power()
    tv.channel_up()
    tv.channel_up()
    tv.channel_up()
    tv.channel_up()
    print(tv)
    tv.channel_down()
    tv.channel_down()
    tv.channel_down()
    tv.channel_down()
    print(tv)
def test_volume():
    tv = Television()
    tv.power()
    tv.volume_up()
    tv.volume_up()
    tv.volume_up()
    tv.volume_up()
    print(tv)
    tv.volume_down()
    tv.volume_down()
    tv.volume_down()
    tv.volume_down()
    print(tv)